MOCK_CANDIDATES = {
    "CAND-001": {
        "candidate_id": "CAND-001",
        "candidate_name": "Aarav Mehta",
        "candidate_email": "aarav.mehta@example.com",
        "job_title": "Machine Learning Engineer",
        "overall_score": 84,
        "score_breakdown": {
            "skills_match": 88,
            "experience_relevance": 80,
            "education_fit": 76,
            "semantic_similarity": 91,
        },
        "matched_skills": ["Python", "Flask", "NLP", "Embeddings", "REST APIs"],
        "missing_skills": ["Vertex AI", "React"],
        "years_experience": 3,
        "jd_summary": "Need a candidate with backend AI integration and dashboard collaboration skills.",
    },
    "CAND-002": {
        "candidate_id": "CAND-002",
        "candidate_name": "Tanay Shirodkar",
        "candidate_email": "neha.kapoor@example.com",
        "job_title": "Machine Learning Engineer",
        "overall_score": 67,
        "score_breakdown": {
            "skills_match": 70,
            "experience_relevance": 66,
            "education_fit": 72,
            "semantic_similarity": 61,
        },
        "matched_skills": ["Python", "Data Analysis", "FastAPI"],
        "missing_skills": ["Flask", "NLP", "Embeddings", "React"],
        "years_experience": 2,
        "jd_summary": "Need a candidate with backend AI integration and dashboard collaboration skills.",
    },
    "CAND-003": {
        "candidate_id": "CAND-003",
        "candidate_name": "Rohan Singh",
        "candidate_email": "rohan.singh@example.com",
        "job_title": "Machine Learning Engineer",
        "overall_score": 41,
        "score_breakdown": {
            "skills_match": 38,
            "experience_relevance": 45,
            "education_fit": 58,
            "semantic_similarity": 40,
        },
        "matched_skills": ["SQL"],
        "missing_skills": ["Python", "Flask", "NLP", "Embeddings", "React"],
        "years_experience": 1,
        "jd_summary": "Need a candidate with backend AI integration and dashboard collaboration skills.",
    },
}
